isEnabled = true
backgroundColor = -1728053248
pressedBackgroundColor = 362789305
keyColor = -65446
pressedKeyColor = -1
rainbowMode = false
rainbowOffset = 9
rainbowSpeed = 4
roundedBackground = false
renderInGui = true
keyShadow = true
cpsType = "NEVER"
displayFactor = 1.0
horizontalSlider = 0
verticalSlider = 400
showMovement = true
showJump = true
showClick = true
